version: '3.9'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - app_network
  nginx: 
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - nextjs
    networks:
      - app_network
  mongo:
    image: mongo
    restart: always
    volumes:
      - data-mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - app_network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - app_network
volumes:
  data-mongo:

networks:
  app_network:
    driver: bridge
